/* confdefs.h */
#define PACKAGE_NAME "dynare"
#define PACKAGE_TARNAME "dynare"
#define PACKAGE_VERSION "4.5-unstable"
#define PACKAGE_STRING "dynare 4.5-unstable"
#define PACKAGE_BUGREPORT ""
#define PACKAGE_URL ""
#define PACKAGE "dynare"
#define VERSION "4.5-unstable"
#define HAVE_BOOST /**/
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_BOOST_GRAPH_ADJACENCY_LIST_HPP 1
#define HAVE_BOOST_ALGORITHM_STRING_TRIM_HPP 1
#define HAVE_BOOST_ALGORITHM_STRING_SPLIT_HPP 1
#define HAVE_BOOST_LEXICAL_CAST_HPP 1
#define BOOST_NO_HASH /**/
#define HAVE_BLAS 1
#define HAVE_LAPACK 1
#define HAVE_PTHREAD_PRIO_INHERIT 1
#define HAVE_PTHREAD 1
#define HAVE_MATLAB 1
